server:
  port: 8080


# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 23321212
    url: jdbc:mysql://192.168.83.123:3306/my-user-center
  application:
    name: user-center
